version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3101:3100"              # Bên host 3100 → trong container cũng là 3100
    volumes:
      - ./backend:/app
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=bcmh_db
      - DB_PORT=3306
      - PORT=3100                # Truyền vào biến PORT cho Node.js

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"              # Host dùng cổng 3307 để tránh trùng
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bcmh_db
    volumes:
      - bcmh_cnpm_mysql_data:/var/lib/mysql

volumes:
  bcmh_cnpm_mysql_data:


